# debug: true
# headless: false
execMode: sync # sync/async
# workers: 4 # Math.min(os.cpus().length, config.workers)

# Whitelisted URI in your developer account spotify app settings that
# Spotify will use to redirect to after user authentication.
redirectUri: https://localhost:7080/callback
# Number of latest videos to extract Spotify tracks from. This number may
# depend on how frequent given channels upload new content
# updateSize: 50
updateIntervalHours: 0.033 # ~2 min
# List of YouTube channels to create playlists for
channels:
  - enesyilmazer
  - enesplus
  - bbcstrictly
  