# debug: false
# Whitelisted URI in your developer account spotify app settings that
# Spotify will use to redirect to after user authentication.
# redirectUri: http://localhost:8080/callback
# headless: true
# Number of latest videos to extract Spotify tracks from. This number may
# depend on how frequent given channels upload new content
# updateSize: 30
# updateIntervalHours: 6
# List of YouTube channels to create playlists for
channels:
  - adelelondon
  - siccasguitars
  # - enesyilmazer
  # - chloechuaviolinist
  